#ifndef HAM_DEFINITIONS_H
#define HAM_DEFINITIONS_H

#include <QString>
#include <QMap>

struct bandData {
    int band_id;
    QString band_name;
    QString band_value;
    QString band_freq;
};

struct modeData {
    int mode_id;
    QString mode_name;
    QString mode_value;
    QString mode_report;
};

struct CountryEntry {
    QString country;
    int cqZone;
    int ituZone;
    QString continent;
    double latitude;
    double longitude;
    double utcOffset;
    QString mainPrefix;
    QStringList prefixes;
};

struct PrefixEntry {
    QString country;
    QString country_code;
    QString continent;
    QString cqzone;
    QString ituzone;
    QString dxcc;
    QString latitude;
    QString longitude;
    QStringList regexList;
};



//Соответствие кодов государств и территорий по ISO 3166-1 (Alpha-2) 346 территорий

const QMap<QString, QString> countryToIso = {
    {"Afghanistan","AF"},
    {"African Italy","IT"},
    {"Agalega & St. Brandon","MU"},
    {"Aland Islands","AX"},
    {"Alaska","US"},
    {"Albania","AL"},
    {"Algeria","DZ"},
    {"American Samoa","AS"},
    {"Amsterdam & St. Paul Is.","FR"},
    {"Andaman & Nicobar Is.","IN"},
    {"Andorra","AD"},
    {"Angola","AO"},
    {"Anguilla","AI"},
    {"Annobon Island","GQ"},
    {"Antarctica","AQ"},
    {"Antigua & Barbuda","AG"},
    {"Argentina","AR"},
    {"Armenia","AM"},
    {"Aruba","AW"},
    {"Ascension Island","SH"},
    {"Asiatic Russia","RU"},
    {"Asiatic Turkey","TR"},
    {"Austral Islands","PF"},
    {"Australia","AU"},
    {"Austria","AT"},
    {"Aves Island","VE"},
    {"Azerbaijan","AZ"},
    {"Azores","PT"},
    {"Bahamas","BS"},
    {"Bahrain","BH"},
    {"Baker & Howland Islands","UM"},
    {"Balearic Islands","ES"},
    {"Banaba Island","KI"},
    {"Bangladesh","BD"},
    {"Barbados","BB"},
    {"Bear Island","SJ"},
    {"Belarus","BY"},
    {"Belgium","BE"},
    {"Belize","BZ"},
    {"Benin","BJ"},
    {"Bermuda","BM"},
    {"Bhutan","BT"},
    {"Bolivia","BO"},
    {"Bonaire","BQ"},
    {"Bosnia-Herzegovina","BA"},
    {"Botswana","BW"},
    {"Bouvet","BV"},
    {"Brazil","BR"},
    {"British Virgin Islands","VG"},
    {"Brunei Darussalam","BN"},
    {"Bulgaria","BG"},
    {"Burkina Faso","BF"},
    {"Burundi","BI"},
    {"Cambodia","KH"},
    {"Cameroon","CM"},
    {"Canada","CA"},
    {"Canary Islands","ES"},
    {"Cape Verde","CV"},
    {"Cayman Islands","KY"},
    {"Central African Republic","CF"},
    {"Central Kiribati","KI"},
    {"Ceuta & Melilla","ES"},
    {"Chad","TD"},
    {"Chagos Islands","IO"},
    {"Chatham Islands","NZ"},
    {"Chesterfield Islands","FR"},
    {"Chile","CL"},
    {"China","CN"},
    {"Christmas Island","CX"},
    {"Clipperton Island","FR"},
    {"Cocos (Keeling) Islands","CC"},
    {"Cocos Island","CR"},
    {"Colombia","CO"},
    {"Comoros","KM"},
    {"Conway Reef","FJ"},
    {"Corsica","FR"},
    {"Costa Rica","CR"},
    {"Cote d'Ivoire","CI"},
    {"Crete","GR"},
    {"Croatia","HR"},
    {"Crozet Island","TF"},
    {"Cuba","CU"},
    {"Curacao","CW"},
    {"Cyprus","CY"},
    {"Czech Republic","CZ"},
    {"Dem. Rep. of the Congo","CD"},
    {"Denmark","DK"},
    {"Desecheo Island","US"},
    {"Djibouti","DJ"},
    {"Dodecanese","GR"},
    {"Dominica","DM"},
    {"Dominican Republic","DO"},
    {"DPR of Korea","KP"},
    {"Ducie Island","PN"},
    {"East Malaysia","MY"},
    {"Easter Island","CL"},
    {"Eastern Kiribati","KI"},
    {"Ecuador","EC"},
    {"Egypt","EG"},
    {"El Salvador","SV"},
    {"England","GB"},
    {"Equatorial Guinea","GQ"},
    {"Eritrea","ER"},
    {"Estonia","EE"},
    {"Ethiopia","ET"},
    {"European Russia","RU"},
    {"European Turkey","TR"},
    {"Falkland Islands","FK"},
    {"Faroe Islands","FO"},
    {"Fed. Rep. of Germany","DE"},
    {"Fernando de Noronha","BR"},
    {"Fiji","FJ"},
    {"Finland","FI"},
    {"France","FR"},
    {"Franz Josef Land","RU"},
    {"French Guiana","GF"},
    {"French Polynesia","PF"},
    {"Gabon","GA"},
    {"Galapagos Islands","EC"},
    {"Georgia","GE"},
    {"Ghana","GH"},
    {"Gibraltar","GI"},
    {"Glorioso Islands","FR"},
    {"Greece","GR"},
    {"Greenland","GL"},
    {"Grenada","GD"},
    {"Guadeloupe","GP"},
    {"Guam","GU"},
    {"Guantanamo Bay","US"},
    {"Guatemala","GT"},
    {"Guernsey","GG"},
    {"Guinea","GN"},
    {"Guinea-Bissau","GW"},
    {"Guyana","GY"},
    {"Haiti","HT"},
    {"Hawaii","US"},
    {"Heard Island","HM"},
    {"Honduras","HN"},
    {"Hong Kong","HK"},
    {"Hungary","HU"},
    {"Iceland","IS"},
    {"India","IN"},
    {"Indonesia","ID"},
    {"Iran","IR"},
    {"Iraq","IQ"},
    {"Ireland","IE"},
    {"Isle of Man","IM"},
    {"Israel","IL"},
    {"Italy","IT"},
    {"ITU HQ","ITU"},
    {"Jamaica","JM"},
    {"Jan Mayen","SJ"},
    {"Japan","JP"},
    {"Jersey","JE"},
    {"Johnston Island","UM"},
    {"Jordan","JO"},
    {"Juan de Nova, Europa","FR"},
    {"Juan Fernandez Islands","CL"},
    {"Kaliningrad","RU"},
    {"Kazakhstan","KZ"},
    {"Kenya","KE"},
    {"Kerguelen Islands","TF"},
    {"Kermadec Islands","NZ"},
    {"Kingdom of Eswatini","SZ"},
    {"Kure Island","UM"},
    {"Kuwait","KW"},
    {"Kyrgyzstan","KG"},
    {"Lakshadweep Islands","IN"},
    {"Laos","LA"},
    {"Latvia","LV"},
    {"Lebanon","LB"},
    {"Lesotho","LS"},
    {"Liberia","LR"},
    {"Libya","LY"},
    {"Liechtenstein","LI"},
    {"Lithuania","LT"},
    {"Lord Howe Island","AU"},
    {"Luxembourg","LU"},
    {"Macao","MO"},
    {"Macquarie Island","AU"},
    {"Madagascar","MG"},
    {"Madeira Islands","PT"},
    {"Malawi","MW"},
    {"Maldives","MV"},
    {"Mali","ML"},
    {"Malpelo Island","CO"},
    {"Malta","MT"},
    {"Mariana Islands","US"},
    {"Market Reef","SE"},
    {"Marquesas Islands","PF"},
    {"Marshall Islands","MH"},
    {"Martinique","MQ"},
    {"Mauritania","MR"},
    {"Mauritius","MU"},
    {"Mayotte","YT"},
    {"Mellish Reef","AU"},
    {"Mexico","MX"},
    {"Micronesia","FM"},
    {"Midway Island","US"},
    {"Minami Torishima","JP"},
    {"Moldova","MD"},
    {"Monaco","MC"},
    {"Mongolia","MN"},
    {"Montenegro","ME"},
    {"Montserrat","MS"},
    {"Morocco","MA"},
    {"Mount Athos","GR"},
    {"Mozambique","MZ"},
    {"Myanmar","MM"},
    {"N.Z. Subantarctic Is.","NZ"},
    {"Namibia","NA"},
    {"Nauru","NR"},
    {"Navassa Island","US"},
    {"Nepal","NP"},
    {"Netherlands","NL"},
    {"New Caledonia","NC"},
    {"New Zealand","NZ"},
    {"Nicaragua","NI"},
    {"Niger","NE"},
    {"Nigeria","NG"},
    {"Niue","NU"},
    {"Norfolk Island","NF"},
    {"North Cook Islands","CK"},
    {"North Macedonia","MK"},
    {"Northern Ireland","GB"},
    {"Norway","NO"},
    {"Ogasawara","JP"},
    {"Oman","OM"},
    {"Pakistan","PK"},
    {"Palau","PW"},
    {"Palestine","PS"},
    {"Palmyra & Jarvis Islands","UM"},
    {"Panama","PA"},
    {"Papua New Guinea","PG"},
    {"Paraguay","PY"},
    {"Peru","PE"},
    {"Peter 1 Island","AQ"},
    {"Philippines","PH"},
    {"Pitcairn Island","PN"},
    {"Poland","PL"},
    {"Portugal","PT"},
    {"Pr. Edward & Marion Is.","ZA"},
    {"Pratas Island","TW"},
    {"Puerto Rico","PR"},
    {"Qatar","QA"},
    {"Republic of Korea","KR"},
    {"Republic of Kosovo","XK"},
    {"Republic of South Sudan","SS"},
    {"Republic of the Congo","CG"},
    {"Reunion Island","RE"},
    {"Revillagigedo","MX"},
    {"Rodriguez Island","MU"},
    {"Romania","RO"},
    {"Rotuma Island","FJ"},
    {"Rwanda","RW"},
    {"Saba & St. Eustatius","NL"},
    {"Sable Island","CA"},
    {"Samoa","WS"},
    {"San Andres & Providencia","CO"},
    {"San Felix & San Ambrosio","CL"},
    {"San Marino","SM"},
    {"Sao Tome & Principe","ST"},
    {"Sardinia","IT"},
    {"Saudi Arabia","SA"},
    {"Scarborough Reef","PH"},
    {"Scotland","GB"},
    {"Senegal","SN"},
    {"Serbia","RS"},
    {"Seychelles","SC"},
    {"Shetland Islands","GB"},
    {"Sicily","IT"},
    {"Sierra Leone","SL"},
    {"Singapore","SG"},
    {"Sint Maarten","SX"},
    {"Slovak Republic","SK"},
    {"Slovenia","SI"},
    {"Solomon Islands","SB"},
    {"Somalia","SO"},
    {"South Africa","ZA"},
    {"South Cook Islands","CK"},
    {"South Georgia Island","GS"},
    {"South Orkney Islands","AQ"},
    {"South Sandwich Islands","GS"},
    {"South Shetland Islands","AQ"},
    {"Sov Mil Order of Malta","MT"},
    {"Spain","ES"},
    {"Spratly Islands",""},
    {"Sri Lanka","LK"},
    {"St. Barthelemy","BL"},
    {"St. Helena","SH"},
    {"St. Kitts & Nevis","KN"},
    {"St. Lucia","LC"},
    {"St. Martin","MF"},
    {"St. Paul Island","CA"},
    {"St. Peter & St. Paul","BR"},
    {"St. Pierre & Miquelon","PM"},
    {"St. Vincent","VC"},
    {"Sudan","SD"},
    {"Suriname","SR"},
    {"Svalbard","SJ"},
    {"Swains Island","AS"},
    {"Sweden","SE"},
    {"Switzerland","CH"},
    {"Syria","SY"},
    {"Taiwan","TW"},
    {"Tajikistan","TJ"},
    {"Tanzania","TZ"},
    {"Temotu Province","SB"},
    {"Thailand","TH"},
    {"The Gambia","GM"},
    {"Timor - Leste","TL"},
    {"Togo","TG"},
    {"Tokelau Islands","TK"},
    {"Tonga","TO"},
    {"Trindade & Martim Vaz","BR"},
    {"Trinidad & Tobago","TT"},
    {"Tristan da Cunha & Gough","SH"},
    {"Tromelin Island","FR"},
    {"Tunisia","TN"},
    {"Turkmenistan","TM"},
    {"Turks & Caicos Islands","TC"},
    {"Tuvalu","TV"},
    {"Uganda","UG"},
    {"UK Base Areas on Cyprus","GR"},
    {"Ukraine","UA"},
    {"United Arab Emirates","AE"},
    {"United Nations HQ","UN"},
    {"United States","US"},
    {"Uruguay","UY"},
    {"US Virgin Islands","VI"},
    {"Uzbekistan","UZ"},
    {"Vanuatu","VU"},
    {"Vatican City","VA"},
    {"Venezuela","VE"},
    {"Vienna Intl Ctr","AT"},
    {"Vietnam","VN"},
    {"Wake Island","UM"},
    {"Wales","GB"},
    {"Wallis & Futuna Islands","WF"},
    {"West Malaysia","MY"},
    {"Western Kiribati","KI"},
    {"Western Sahara","EH"},
    {"Willis Island","AU"},
    {"Yemen","YE"},
    {"Zambia","ZM"},
    {"Zimbabwe","ZW"}
};


#endif // HAM_DEFINITIONS_H
