name: macOS builds

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          - arch: arm64
            runner: macos-14
          - arch: x86_64
            runner: macos-13
    runs-on: ${{ matrix.runner }}
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt 5 and pkgconf
        run: |
          brew install qt@5 pkgconf
          QT_PREFIX="$(brew --prefix qt@5)"
          echo "QT_PREFIX=$QT_PREFIX" >> "$GITHUB_ENV"
          echo "$QT_PREFIX/bin" >> "$GITHUB_PATH"
          echo "PKG_CONFIG_PATH=$QT_PREFIX/lib/pkgconfig" >> "$GITHUB_ENV"
          echo "LDFLAGS=-L$QT_PREFIX/lib" >> "$GITHUB_ENV"
          echo "CPPFLAGS=-I$QT_PREFIX/include" >> "$GITHUB_ENV"
          "$QT_PREFIX/bin/qmake" -v

      - name: Configure
        run: |
          BUILD_DIR="build-${{ matrix.arch }}"
          mkdir -p $BUILD_DIR
          cd $BUILD_DIR
          qmake ../QSOSU-desktop-app.pro CONFIG+=release QMAKE_APPLE_DEVICE_ARCHS=${{ matrix.arch }}

      - name: Build
        run: |
          BUILD_DIR="build-${{ matrix.arch }}"
          cd $BUILD_DIR
          make -j"$(sysctl -n hw.logicalcpu)"

      - name: Deploy Qt frameworks if .app exists
        run: |
          BUILD_DIR="build-${{ matrix.arch }}"
          cd $BUILD_DIR
          APP_PATH="$(find . -name "*.app" -maxdepth 3 -print -quit || true)"
          if [ -n "$APP_PATH" ]; then
            macdeployqt "$APP_PATH" -always-overwrite
            ditto -c -k --keepParent "$APP_PATH" QSOSU-logger-macOS-${{ matrix.arch }}.zip
          else
            BIN="$(find . -type f -perm -111 -name 'QSOSU-desktop-app' -print -quit || true)"
            if [ -n "$BIN" ]; then
              tar -czf QSOSU-logger-macOS-${{ matrix.arch }}.tar.gz "$BIN"
            fi
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QSOSU-logger-macOS-${{ matrix.arch }}
          path: |
            build-${{ matrix.arch }}/QSOSU-logger-macOS-${{ matrix.arch }}.zip
            build-${{ matrix.arch }}/QSOSU-logger-macOS-${{ matrix.arch }}.tar.gz
