name: Build & attach (Ubuntu .deb + Windows .exe 32/64)

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write  # нужно для загрузки ассетов в релиз

env:
  APP_NAME: QSOSU-desktop-app
  HUMAN_NAME: "QSO Logger"

jobs:
  # вычисляем версии из тега
  prep:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.v.outputs.version }}
      version_stripped: ${{ steps.v.outputs.version_stripped }}
    steps:
      - id: v
        run: |
          v="${GITHUB_REF_NAME}"        # например v1.2.3
          vs="${v#v}"                   # убираем префикс v
          echo "version=$v" >> "$GITHUB_OUTPUT"
          echo "version_stripped=$vs" >> "$GITHUB_OUTPUT"

  # ===================== Ubuntu (.deb) =====================
  ubuntu-deb:
    runs-on: ubuntu-22.04
    needs: [prep]
    env:
      VERSION_STRIPPED: ${{ needs.prep.outputs.version_stripped }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt5 toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools \
            libqt5serialport5-dev libgl1-mesa-dev fakeroot
          qmake -v
      - name: Build (qmake + make)
        run: |
          mkdir -p build && cd build
          qmake ../QSOSU-desktop-app.pro CONFIG+=release
          make -j"$(nproc)"
          cd ..
          if [ -x build/${{ env.APP_NAME }} ]; then
            echo "BIN=build/${{ env.APP_NAME }}" >> $GITHUB_ENV
          elif [ -x build/release/${{ env.APP_NAME }} ]; then
            echo "BIN=build/release/${{ env.APP_NAME }}" >> $GITHUB_ENV
          else
            echo "Binary not found" && exit 1
          fi
      - name: Stage .deb
        run: |
          APP_ID=qsosu-logger
          ROOT="$PWD/pkgroot"
          install -d "$ROOT/DEBIAN" "$ROOT/usr/bin" "$ROOT/usr/share/applications"
          install -m 0755 "${BIN}" "$ROOT/usr/bin/${{ env.APP_NAME }}"
          cat > "$ROOT/usr/share/applications/${APP_ID}.desktop" <<'EOF'
          [Desktop Entry]
          Name=QSO Logger
          Comment=QSOSU Logger (Qt)
          Exec=/usr/bin/QSOSU-desktop-app
          Icon=utilities-terminal
          Terminal=false
          Type=Application
          Categories=Utility;
          EOF
          cat > "$ROOT/DEBIAN/control" <<EOF
          Package: ${APP_ID}
          Version: ${{ env.VERSION_STRIPPED }}
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: Unknown <noreply@example.com>
          Depends: libqt5widgets5, libqt5gui5, libqt5core5a, libqt5serialport5, libc6, libstdc++6
          Description: ${HUMAN_NAME} (Qt-based logger)
           Built from qsosu/logger.
          EOF
      - name: Build .deb
        run: |
          DEB="qsosu-logger_${{ env.VERSION_STRIPPED }}_amd64.deb"
          fakeroot dpkg-deb --build pkgroot "$DEB"
          echo "DEB=$DEB" >> $GITHUB_ENV
      - name: Upload Ubuntu artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-deb
          path: ${{ env.DEB }}

  # ===================== Windows x64 =====================
  windows-exe-64:
    runs-on: windows-2022
    needs: [prep]
    env:
      VERSION_STRIPPED: ${{ needs.prep.outputs.version_stripped }}
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install aqtinstall and NSIS
        shell: pwsh
        run: |
          pip install aqtinstall
          choco install nsis -y
      - name: Install Qt 5.15.2 (msvc2019_64)
        shell: pwsh
        run: |
          aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 --outputdir C:/Qt
          "C:/Qt/5.15.2/msvc2019_64/bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Configure (qmake)
        shell: cmd
        run: |
          mkdir build
          cd build
          qmake ..\QSOSU-desktop-app.pro CONFIG+=release
      - name: Build (nmake)
        shell: cmd
        run: |
          cd build
          nmake /S
      - name: Deploy Qt runtime
        shell: cmd
        run: |
          cd build
          if not exist release\${{ env.APP_NAME }}.exe exit /b 1
          windeployqt release\${{ env.APP_NAME }}.exe --compiler-runtime --release
      - name: Create NSIS installer
        shell: pwsh
        run: |
          makensis /V2 /NOCD /DVERSION=${{ env.VERSION_STRIPPED }} `
            /X"OutFile QSOSU-desktop-app-${{ env.VERSION_STRIPPED }}-win64.exe" installer.nsi
          Rename-Item "QSOSU-desktop-app-installer.exe" "QSOSU-desktop-app-${{ env.VERSION_STRIPPED }}-win64.exe" -Force -ErrorAction SilentlyContinue
      - name: Upload Windows x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe-64
          path: QSOSU-desktop-app-${{ env.VERSION_STRIPPED }}-win64.exe

  # ===================== Windows x86 =====================
  windows-exe-32:
    runs-on: windows-2022
    needs: [prep]
    env:
      VERSION_STRIPPED: ${{ needs.prep.outputs.version_stripped }}
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install aqtinstall and NSIS
        shell: pwsh
        run: |
          pip install aqtinstall
          choco install nsis -y
      - name: Install Qt 5.15.2 (msvc2019)
        shell: pwsh
        run: |
          aqt install-qt windows desktop 5.15.2 win32_msvc2019 --outputdir C:/Qt
          "C:/Qt/5.15.2/msvc2019/bin" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Configure (qmake)
        shell: cmd
        run: |
          mkdir build
          cd build
          qmake ..\QSOSU-desktop-app.pro CONFIG+=release
      - name: Build (nmake)
        shell: cmd
        run: |
          cd build
          nmake /S
      - name: Deploy Qt runtime
        shell: cmd
        run: |
          cd build
          if not exist release\${{ env.APP_NAME }}.exe exit /b 1
          windeployqt release\${{ env.APP_NAME }}.exe --compiler-runtime --release
      - name: Create NSIS installer
        shell: pwsh
        run: |
          makensis /V2 /NOCD /DVERSION=${{ env.VERSION_STRIPPED }} `
            /X"OutFile QSOSU-desktop-app-${{ env.VERSION_STRIPPED }}-win32.exe" installer.nsi
          Rename-Item "QSOSU-desktop-app-installer.exe" "QSOSU-desktop-app-${{ env.VERSION_STRIPPED }}-win32.exe" -Force -ErrorAction SilentlyContinue
      - name: Upload Windows x86 artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe-32
          path: QSOSU-desktop-app-${{ env.VERSION_STRIPPED }}-win32.exe

  # ===================== Publish to Release =====================
  publish:
    runs-on: ubuntu-22.04
    needs: [prep, ubuntu-deb, windows-exe-64, windows-exe-32]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - run: ls -laR dist
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*
          tag_name: ${{ needs.prep.outputs.version }}
          append_body: true
          fail_on_unmatched_files: false
